language: php

php:
  - 7
  - 7.1
  - hhvm

before_script:
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - ./vendor/bin/humbug

matrix:
  allow_failures:
    - php: hhvm

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
